import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1788175179604 implements MigrationInterface {
    name = 'InitialMigration1788175179604'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_user"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "fk_payments_order"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "fk_refunds_payment"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "fk_variant_product"`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" DROP CONSTRAINT "fk_payment_attempts_payment"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_order"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_variant"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "fk_inventory_variant"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "fk_cr_coupon"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "fk_cr_user"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "fk_carts_user"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_cart"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_variant"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "fk_addresses_user"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "fk_pc_product"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "fk_pc_category"`);
        await queryRunner.query(`DROP INDEX "public"."uq_coupon_redemptions_coupon_user"`);
        await queryRunner.query(`DROP INDEX "public"."uq_cart_item_cart_variant"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME COLUMN "user_id" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "payments" RENAME COLUMN "order_id" TO "orderId"`);
        await queryRunner.query(`ALTER TABLE "refunds" RENAME COLUMN "payment_id" TO "paymentId"`);
        await queryRunner.query(`ALTER TABLE "product_variants" RENAME COLUMN "product_id" TO "productId"`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" RENAME COLUMN "payment_id" TO "paymentId"`);
        await queryRunner.query(`ALTER TABLE "carts" RENAME COLUMN "user_id" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "addresses" RENAME COLUMN "user_id" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_variant_id"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP COLUMN "coupon_id"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "cart_id"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "product_variant_id"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "pk_product_categories"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "pk_product_categories" PRIMARY KEY ("category_id")`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "pk_product_categories"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "orderId" uuid`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "productVariantId" uuid`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD "couponId" uuid`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "cartId" uuid`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "productVariantId" uuid`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD "productsId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "PK_3d78977f2f60b4f7a1d833e4181" PRIMARY KEY ("productsId")`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD "categoriesId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "PK_3d78977f2f60b4f7a1d833e4181"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "PK_bc0bce5de12ebedb70ddcb3bb34" PRIMARY KEY ("productsId", "categoriesId")`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "productId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" ALTER COLUMN "paymentId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "product_variant_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_coupon_redemptions_coupon_user" ON "coupon_redemptions" ("couponId", "userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_cart_item_cart_variant" ON "cart_items" ("cartId", "productVariantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d78977f2f60b4f7a1d833e418" ON "product_categories" ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c642709e6ad4582ed11aca458f" ON "product_categories" ("categoriesId") `);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "CHK_6e5d794f7711186091b3156024" CHECK ("quantity" > 0)`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "CHK_57c6a3eb67500d319c5716e02c" CHECK ("quantity" >= 0)`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "CHK_f00f0d9fe3a07ebd89324900d0" CHECK ("quantity" > 0)`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_a276dea330e561499e4a6e1b309" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" ADD CONSTRAINT "FK_6657761cef2e4909ca5c6cd2010" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_33ae169110d73844dad2a17faca" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_26b8ad24ace2974b2b6c2047d3a" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_21b5ef20634735e39029e178e7e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_98ba4bbf6e3611d2062b898f5c1" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_95c93a584de49f0b0e13f753630" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_3d78977f2f60b4f7a1d833e4181" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_c642709e6ad4582ed11aca458f9" FOREIGN KEY ("categoriesId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_c642709e6ad4582ed11aca458f9"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_3d78977f2f60b4f7a1d833e4181"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_95c93a584de49f0b0e13f753630"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_98ba4bbf6e3611d2062b898f5c1"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_21b5ef20634735e39029e178e7e"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_26b8ad24ace2974b2b6c2047d3a"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_33ae169110d73844dad2a17faca"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" DROP CONSTRAINT "FK_6657761cef2e4909ca5c6cd2010"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_a276dea330e561499e4a6e1b309"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "CHK_f00f0d9fe3a07ebd89324900d0"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "CHK_57c6a3eb67500d319c5716e02c"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "CHK_6e5d794f7711186091b3156024"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c642709e6ad4582ed11aca458f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d78977f2f60b4f7a1d833e418"`);
        await queryRunner.query(`DROP INDEX "public"."uq_cart_item_cart_variant"`);
        await queryRunner.query(`DROP INDEX "public"."uq_coupon_redemptions_coupon_user"`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "product_variant_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" ALTER COLUMN "paymentId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "productId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "PK_bc0bce5de12ebedb70ddcb3bb34"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "PK_3d78977f2f60b4f7a1d833e4181" PRIMARY KEY ("productsId")`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP COLUMN "categoriesId"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "PK_3d78977f2f60b4f7a1d833e4181"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP COLUMN "productsId"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "productVariantId"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "cartId"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP COLUMN "couponId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "productVariantId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "pk_product_categories" PRIMARY KEY ("category_id")`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD "product_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "pk_product_categories"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "pk_product_categories" PRIMARY KEY ("product_id", "category_id")`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "product_variant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "cart_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD "coupon_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_variant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "order_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" RENAME COLUMN "userId" TO "user_id"`);
        await queryRunner.query(`ALTER TABLE "carts" RENAME COLUMN "userId" TO "user_id"`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" RENAME COLUMN "paymentId" TO "payment_id"`);
        await queryRunner.query(`ALTER TABLE "product_variants" RENAME COLUMN "productId" TO "product_id"`);
        await queryRunner.query(`ALTER TABLE "refunds" RENAME COLUMN "paymentId" TO "payment_id"`);
        await queryRunner.query(`ALTER TABLE "payments" RENAME COLUMN "orderId" TO "order_id"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME COLUMN "userId" TO "user_id"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_cart_item_cart_variant" ON "cart_items" ("cart_id", "product_variant_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_coupon_redemptions_coupon_user" ON "coupon_redemptions" ("coupon_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "fk_pc_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "fk_pc_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "fk_addresses_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_variant" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_cart" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "fk_carts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "fk_cr_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "fk_cr_coupon" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "fk_inventory_variant" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_variant" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" ADD CONSTRAINT "fk_payment_attempts_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "fk_variant_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "fk_refunds_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
